# =================================================================
# PROYECTO: Sistema IoT Autónomo - Cuenca Chancay-Huaral
# ARCHIVO DE CONFIGURACIÓN DEL BROKER MQTT (mosquitto.conf)
# ENFOQUE: Metodología STRIDE y Mosquitto Go Auth
# VERSIÓN: Laboratorio IoT (Dockerizado)
# =================================================================

# --- 1. Conectividad Básica ---
listener 1883 0.0.0.0

# --- 2. Mitigación de DoS y Estabilidad ---
max_connections 50
max_queued_messages 1000
message_size_limit 2048
persistence true
persistence_location /mosquitto/data/

# --- 3. Seguridad e Integridad (STRIDE - Mosquitto Go Auth) ---
allow_anonymous false

# Ruta del plugin dentro del contenedor oficial de Go Auth
auth_plugin /mosquitto/go-auth.so

# Configurar el backend (PostgreSQL)
auth_opt_backends postgres
auth_opt_pg_host db_postgres
auth_opt_pg_port 5432
auth_opt_pg_dbname chancayhuaral_auth
auth_opt_pg_user adminChancayHuaral
auth_opt_pg_password adminChancayHuaral123
auth_opt_hasher bcrypt

# Consultas SQL para el plugin
auth_opt_pg_userquery SELECT password_hash FROM test_user WHERE username = $1
auth_opt_pg_aclquery SELECT topic FROM test_acl WHERE username = $1 AND (rw = $2 OR rw = 3)