# =================================================================
# PROYECTO: Sistema IoT Autónomo - Cuenca Chancay-Huaral
# ARCHIVO DE CONFIGURACIÓN DEL BROKER MQTT (mosquitto.conf)
# ENFOQUE: Metodología STRIDE (Mitigación de Spoofing y Tampering)
# =================================================================

# --- Conectividad Básica (Topología Estrella) ---
# Escuchar en todas las interfaces de red locales (Wi-Fi de la PC)
listener 1883 0.0.0.0

# --- Seguridad e Integridad (STRIDE - Autenticación) ---
# Desactivar por completo el acceso anónimo. 
# Nadie puede conectarse a la red de la Smart City sin credenciales.
allow_anonymous false

# Ruta al archivo oculto que almacena los usuarios y contraseñas cifradas
# (Evita la suplantación de identidad o 'Spoofing' de nodos sensores)
password_file ./configuration_usuarios.txt

# --- Optimización de Mensajes ---
# Guardar estados en memoria para garantizar disponibilidad (Disponibilidad frente a DoS)
persistence true
persistence_location ./data/

# Formato de logs para auditoría de conexiones sospechosas
log_dest stderr
log_type error
log_type warning
log_type notice
log_type information