version: '3.8'

services:
  db_postgres:
    image: postgres:13-alpine
    container_name: bd_credenciales_iot
    environment:
      POSTGRES_DB: chancayhuaral_auth
      POSTGRES_USER: adminChancayHuaral
      POSTGRES_PASSWORD: adminChancayHuaral123
    volumes:
      # Inyecta el script para crear las tablas al iniciar la BD por primera vez
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - iot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminChancayHuaral -d chancayhuaral_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    container_name: broker_chancay_huaral
    depends_on:
      db_postgres:
        condition: service_healthy 
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot_network

  motor_ia:
    build:
      context: ../Capa_3_Soporte_A_Servicios/laboratorio 
      dockerfile: Dockerfile
    container_name: motor_ia_chancay
    depends_on:
      mosquitto: 
        condition: service_started
    networks:
      - iot_network
  
  node_red_app:
    build:
      context: ../Capa_4_Aplicacion/laboratorio 
      dockerfile: Dockerfile.nodered
    container_name: app_nodered_chancay
    ports:
      - "1880:1880"
    volumes:
      - ../Capa_4_Aplicacion/laboratorio/data:/data 
    environment:
      - TZ=America/Lima
      - AI_API_KEY=tu_token_aqui
    networks:
      - iot_network
    depends_on:
      - mosquitto
      - motor_ia

networks:
  iot_network:
    driver: bridge