version: '3.8'

services:
  db_postgres:
    image: postgres:13-alpine
    container_name: bd_credenciales_iot
    environment:
      POSTGRES_DB: chancayhuaral_auth
      POSTGRES_USER: adminChancayHuaral
      POSTGRES_PASSWORD: adminChancayHuaral123
    volumes:
      # Inyecta el script para crear las tablas al iniciar la BD por primera vez
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Guarda los datos en tu disco duro local/Codespace
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - iot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminChancayHuaral -d chancayhuaral_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  simulador_mqtt:
    build:
      context: ../../Capa_2_Red/laboratorio
      dockerfile: Dockerfile.simulator
    container_name: sim_mqtt_chancay
    networks:
      - iot_network
    depends_on:
      - mosquitto

  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    container_name: broker_chancay_huaral
    depends_on:
      db_postgres:
        condition: service_healthy 
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    networks:
      - iot_network

  motor_ia:
    build:
      context: ../../Capa_3_Soporte_A_Servicios/laboratorio 
      dockerfile: Dockerfile
    container_name: motor_ia_chancay
    ports:
      - "8000:8000"
    environment:
      # Inyectamos la base de datos de producción para que guarde el histórico real
      - DATABASE_URL=postgresql://adminChancayHuaral:adminChancayHuaral123@shortline.proxy.rlwy.net:21301/chancayhuaral_auth
    networks:
      - iot_network
  
  node_red_app:
    build:
      context: ../../Capa_4_Aplicacion/laboratorio 
      dockerfile: Dockerfile.nodered
    container_name: app_nodered_chancay
    ports:
      - "1880:1880"
    volumes:
      - ../../Capa_4_Aplicacion/laboratorio/nodered-data:/data
    environment:
      - TZ=America/Lima
      - AI_API_KEY=AQ.Ab8RN6Knm7IFz7SzdIZMRJJGmXKJNvmKIEd0kG1RHdloYXv0GQ
      - WA_INSTANCE=123456                      # <--- Tu Id de Instancia de Green-API
      - WA_TOKEN=abcdef1234567890yourtoken2026   # <--- Tu Token Secreto de Green-API
      - WA_RECIPIENT=519998887777@c.us            # <--- Número que recibirá las alertas
      - MQTT_BROKER_HOST=hayabusa.proxy.rlwy.net
      - MQTT_BROKER_PORT=35329
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - iot_network
    depends_on:
      - mosquitto
      - motor_ia

  frontend:
    build:
      context: ../../Capa_4_Aplicacion/laboratorio/frontend
      dockerfile: Dockerfile
    container_name: yaku_qhawaq_frontend
    ports:
      - "8080:80"
    networks:
      - iot_network
    depends_on:
      - node_red_app

networks:
  iot_network:
    driver: bridge

volumes:
  mosquitto_data:
  postgres_data: 
